services:
  postgres:
    image: postgres:latest
    container_name: crm-postgres
    environment:
      POSTGRES_DB: crm
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./src/main/resources/db/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./src/main/resources/db/test-data.sql:/docker-entrypoint-initdb.d/2-data.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
